### ISSUE TITLE
Missing package content

### ISSUE THREAD

**Issue by bobsummerwill** [kitsilanosoftware/EAWebKit#5]
EA are the only people who can resolve this issue.
- Code which is platform-specific is being blanket stripped for all except the published platforms (pc32, pc64, ps4 and xbone).   Even the supported platforms varies across EAWebKit releases.
- Missing original build files (only generated VXCPROJ/SLNs shipped)
- Missing documentation
- Missing changelogs
- Missing unit-tests
- Missing examples

**Comment by chrisjubb** [comment]
Hi. Have you been able to throw a sample application together that uses the EAWebkit.dll that is created?

**Comment by bobsummerwill** [comment]
Hey Chris, 
I've done nothing further on this since the releases because there was essentially no interest.  There have been no further EAWebkit releases from EA at http://gpl.ea.com.  I doubt that they have stopped internal development of that technology, but if the development is happening then it is now happening in private.   Perhaps they got scared out of open source good citizenship by this project?   Or perhaps not.   Who knows. 

To answer your question -  No.   I have no direct need for these libraries in my current development  focus (mobile and wearable)  but though others would have -  hence the releases.   Looks like I was wrong.

Have you tried building something yourself?

**Comment by chrisjubb** [comment]
I've got the DLL to build on Windows in Visual Studio 2013.
I'm now writing a simple test application to try an initialise the library. I imagine there will be masses of work to do though.

Here's a snippet of what I've got so far (link with EAWebkitd.lib and run in the folder that the dll lives in). This crashes though because nothing is implemented:

```
    typedef EA::WebKit::EAWebKitLib*(*PFNCREATEINSTANCE)();

    printf("Loading dll\n");
    HMODULE h = LoadLibrary(TEXT("EAWebKitd.dll"));
    printf("handle = %d\n", h);

    PFNCREATEINSTANCE pfn = (PFNCREATEINSTANCE)GetProcAddress(h, "CreateEAWebkitInstance");
    if (!pfn) {
        printf("Error - cannot find entry point\n");
        exit(1);
    }

    printf("Creating EAWebKitLib\n");
    EA::WebKit::EAWebKitLib* lib = pfn();

    printf("result = %d initing\n", lib);

    EA::WebKit::AppCallbacks appCallbacks;
    appCallbacks.atomicDecrement = NULL; // todo implement
    appCallbacks.atomicIncrement = NULL; // todo implement
    appCallbacks.cryptRandomValue = NULL; // todo implement
    appCallbacks.stackBase = NULL; // todo implement
    appCallbacks.timer = NULL; // todo implement

    EA::WebKit::AppSystems appSystems;
    appSystems.mAllocator = NULL; // todo implement
    appSystems.mEAWebkitClient = NULL; // todo implement
    appSystems.mFileSystem = NULL; // todo implement
    appSystems.mTextSystem = NULL; // todo implement
    appSystems.mThreadSystem = NULL; // todo implement

    lib->Init(&appCallbacks, &appSystems);

    printf("ticking\n");

    lib->Tick();

    printf("shutting down\n");

    lib->Shutdown();
    lib->Destroy();
```

**Comment by bobsummerwill** [comment]
Something else for you to bear in mind is that it has become more-and-more apparent that Webkit is a pretty dying project.   Google jumped ship with the Bink fork nearly two years ago now, and Blink, Chromium and Crosswalk have come on leaps and bounds since.

http://www.i-programmer.info/news/86-browsers/7165-the-astonishing-progress-of-blink.html

Depending on what platforms you are looking to develop for (just PC for now?) you might be better served by looking at Google's technologies.

Mozilla are driving Gecko / Firefox / Firefox OS hard, with WebGL and asm.js support.

Google are driving Blink / Chrome / Chromium / Chrome OS / Crosswalk hard, with WebGL and AOT compilation in a different form.

Microsoft have created Spartan and are driving hard on that.

Apple are tepid with Webkit.   Safari is meh.

Apple are tepid

**Comment by chrisjubb** [comment]
Yes I think that EAWebKit thing is a non starter. There isn't support for it even if I do get it working.
I got the Chromium Embedding Framework thing and am looking at that. That looks like it's updated really regularly.
I want to get it working everywhere - PC, consoles, etc.

Thanks for replying, I thought this project looked pretty untouched :)

**Comment by bobsummerwill** [comment]
No problem.  Good luck!

**Comment by bobsummerwill** [comment]
Abandoned, because of official EA open sourcing  - https://github.com/electronicarts
